// Generated by CoffeeScript 1.6.3
(function() {
  var createChebo, script, scripts;

  scripts = ["//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js", "//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.4/underscore-min.js", "//cdnjs.cloudflare.com/ajax/libs/backbone.js/0.9.10/backbone-min.js"];

  _.each(scripts, function(src) {
    var script;
    script = document.createElement("script");
    script.src = src;
    return document.body.appendChild(script);
  });

  createChebo = function() {
    var Chebo;
    Chebo = _.isUndefined(Chebo) ? {} : Chebo;
    Chebo.jQuery = jQuery.noConflict(true);
    Chebo.Backbone = Backbone.noConflict();
    Chebo.underscore = _.noConflict();
    return this.Chebo = Chebo;
  };

  script = document.createElement("script");

  script.appendChild(document.createTextNode("var createChebo = " + createChebo.toString()));

  document.body.appendChild(script);

}).call(this);
